# Generated by Django 2.2.2 on 2019-12-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('InterviewDate', models.DateTimeField()),
                ('Skills', models.CharField(blank=True, max_length=500)),
                ('HrNumber', models.IntegerField(blank=True, max_length=12)),
            ],
        ),
    ]
