# Generated by Django 2.2.2 on 2019-12-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcafinalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='InterviewLocation',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='JobDescription',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
