# Generated by Django 2.2.2 on 2019-12-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcafinalapp', '0002_auto_20191229_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('studentSkills', models.CharField(max_length=500)),
                ('Nationality', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=50)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcafinalapp.Company')),
            ],
        ),
    ]
